### ISSUE TITLE
Registering bundle failed? 

### ISSUE THREAD

**Issue by ewitczak** [webfactory/exceptions-bundle#18]
Hi there,

after installing your bundle, I wanted to clear my cache (with & without warmup).
On the cli I'll get this error:

[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                 
  Cannot load resource "@WebfactoryExceptionsBundle/Controller/TestController.php". Make sure the "WebfactoryExceptionsBundle" bundle is corr  
  ectly registered and loaded in the application kernel class.  

Same on http://{host}/app_dev.php/_error/404
Everything else is working.
I added the mentioned code at my AppKernel and the routes in routing_dev.yml.

Well, the Routes are fine and in phpStorm (with sf2 Plugin) they are all accessible.
Do you have any idea, how I can solve this issue? 

Thanks,
Erik

**Comment by MalteWunsch** [comment]
Close due to inactivity
