### ISSUE TITLE
No longer needed on Symfony 2.6?

### ISSUE THREAD

**Issue by bkosborne** [webfactory/exceptions-bundle#25]
Seems like this bundle isn't needed for Symf 2.6: http://symfony.com/blog/new-in-symfony-2-6-error-page-previews

If that's true, can you update the README to indicate as such?

**Comment by MalteWunsch** [comment]
Update: Symfony 2.6.2, which hopefully fixes the inclusion, is not released yet. Updating the README makes most sense afterwards.
